name: ci
on: [push, pull_request]
jobs:

  test-python-service:
    name: Test Python service
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout code
        uses: actions/checkout@v2
    
    - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

    - name: initialize submodules
        run: git submodule update --init --recursive --progress --depth 1

    - name: build docker image
        run: |
          cd python
          ./build_docker_image.sh "${GITHUB_REF##*/}"

    - name: run tests
        run: |
          docker run --rm dictation-client-python:"${GITHUB_REF##*/}" ./tests/test_service_with_script_for_local_usage.sh
          ./python/tests/test_service_with_script_for_docker_usage.sh dictation-client-python:"${GITHUB_REF##*/}"


  test-cpp-service:
    name: Test C++ service
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout code
        uses: actions/checkout@v2

    - name: initialize submodules
        run: git submodule update --init --recursive --progress --depth 1

    - name: build docker image
      run: |
        cd cpp
        ./build_docker_image.sh "${GITHUB_REF##*/}"

    - name: run tests
      run: |
        docker run --rm dictation-client-cpp:"${GITHUB_REF##*/}" ./cpp/tests/test_service_with_script_for_local_usage.sh
        ./cpp/tests/test_service_with_script_for_docker_usage.sh dictation-client-cpp:"${GITHUB_REF##*/}"
        